name: Generate SBOM

on:
  pull_request:
    branches:
      - main
    paths:
      - package-lock.json
      - .github/workflows/generate_sbom.yml
  push:
    branches:
      - main
    paths:
      - package-lock.json
      - .github/workflows/generate_sbom.yml

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Generate app SBOM
        uses: cds-snc/security-tools/.github/actions/generate-sbom@4368a5486da1f0bb698ffe717687612d4231c6cd # v1.1.7
        with:
          dependency_track_api_key: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
          project_name: notification-pr-bot/app
          project_type: node        
